### ISSUE TITLE
Codon harmonizer suggestion

### ISSUE THREAD

**Issue by mlajoie** [weitzner/codon_harmony#23]
- Make human the default
- Include example command line with suggested flags
- Is there a way to save standard flags so that we don't need to type them (or paste them) every time?

**Comment by weitzner** [comment]
For flags and other usage information, see: https://codon-harmony.readthedocs.io/en/latest/usage.html

One way to create custom flags is to do the following:

In your runner file, add a list of those flags and pass them into the runner function:
```python
import codon_harmony
args_to_parse = "--input=IN.fasta --output=OUT.fasta --host=9606 --max_relax=0.07".split()
codon_harmony.runner(args_to_parse)
```

Does that work for you?

**Comment by weitzner** [comment]
It looks like we have this up and running. I am going to close this issue.
