### ISSUE TITLE
Unable to create suitable DNA sequence for input sequence 

### ISSUE THREAD

**Issue by jocelynnpearl** [weitzner/codon_harmony#24]
I submitted the following: 
`python runner.py --input /Users/jpearl/codon_tools/tagGFP-seq2.fasta --output tagGFP-output.fasta --host 9606`
I received the following message:
`WARNING:codon_harmony.codon_harmony:Unable to create suitable DNA sequence for input sequence 1.`

>tagGFP2
MSGGEELFAGIVPVLIELDGDVHGHKFSVRGEGEGDADYGKLEIKFICTTGKLPVPWPTL
VTTLCYGIQCFARYPEHMKMNDFFKSAMPEGYIQERTIQFQDDGKYKTRGEVKFEGDTLV
NRIELKGKDFKEDGNILGHKLEYSFNSHNVYIRPDKANNGLEANFKTRHNIEGGGVQLAD
HYQTNVPLGDGPVLIPINHYLSTQTKISKDRNEARDHMVLLESFSACCHTHGMDELYR

**Comment by weitzner** [comment]
This happens when the harmonizer cannot reconcile all of the optimizations while matching the host profile within the specified tolerance. In this case, you can often increase the tolerance a bit, or we can chat about some other possible strategies to perform the optimizations.

**Comment by jocelynnpearl** [comment]
What do you mean by 'increase the tolerance a bit' - is this the --max-relax function?

**Comment by weitzner** [comment]
Yep! max-relax is the tolerated deviation from the host codon usage profile, and the default value is 0.10. Increasing to 0.20 will likely help your sequence through, but there are obviously concerns about that value being too high. Where that line is remains to be determined.

**Comment by weitzner** [comment]
See the use of default flags in #23.
